### PR TITLE
LPS-186327 UpgradeJavaServiceReferenceAnnotationCheck

### PR DESCRIPTION
**Pull request by TamyrisTorres**
LPS-186327 - https://issues.liferay.com/browse/LPS-186327

Hi Kevin!
I'm new to this UpgrageChecks project. I'm a send my first code to you.

This is a check for through the replace will change the annotation @ServiceReference by @Reference

So, please, Would you review this pull request?

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hi @TamyrisTorres, welcome to the team!

**Comment by kevhlee** [comment]
Taking a look.

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
Hi @TamyrisTorres, your pull request looks pretty good. The logic makes sense and the code was relatively clean. There is one weird thing which is the usage of `JavaSourceUtil.getMethodCall()`. While it technically works, it is confusing because an annotation is not quite a method call.

See here: <https://github.com/TamyrisTorres/liferay-portal/pull/22>

**Pull request closed without merging**
