### PR TITLE
LPS-186060

### PR DESCRIPTION
**Pull request by kevhlee**
From @nicolas-sss:

>Ticket: https://issues.liferay.com/browse/LPS-186060
>
>Hi Kevin!
>
>This is a check for the MultiVMPoolUtil class and the actual pattern that we have, but possibly other patterns will come in the future. Also, this is the check that we talked about not being able to retrieve types for cast in some cases and relying on user input at the end. And now is with the necessary change to test both messages and content.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
ci:forward

**Comment by nicolas-sss** [comment]
ci:forward

**Comment by kevhlee** [comment]
@nicolas-sss, let me make one more small change.

**Comment by kevhlee** [comment]
Actually, nevermind @nicolas-sss. The SF test failure looks unrelated. I will manually forward.

**Comment by kevhlee** [comment]
Manually forwarded here: <https://github.com/brianchandotcom/liferay-portal/pull/136566>

**Pull request closed without merging**
