### PR TITLE
LPS-187960 Update usage of ModelListener

### PR DESCRIPTION
**Pull request by TamyrisTorres**
Ticket: https://liferay.atlassian.net/browse/LPS-187960

Hi Kevin!

For this check, we need to add the parameter (T originalModel).
So, we change this ModelListener.onAfterUpdate(T model) by this ModelListener.onAfterUpdate(T originalModel, T model).

I used your suggestion to use JavaMethod but I keep using JAVA_CLASS, because the return was just one method in the class, and didn't return the other methods. 
So, I preferred to use de JavaMethod to rebuild the parameters. 

Can you review it, please?

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
See here: <https://github.com/kevhlee/liferay-portal/pull/107>

**Pull request closed without merging**
