### PR TITLE
LPS-185318

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
Ticket: [LPS-185318](https://issues.liferay.com/browse/LPS-185318)
Hi Kevin!
Now me and @nicolas-sss are working together in UpgradeChecks.
This is a check for impls the class ServiceTrackerList. This pattern is about the quantity of arguments inside <> of ServiceTrackerList. The quantity of arguments was replaced from two to one. Please look at the UpgradeJavaServiceTrackerListCheck.testjava files if you have doubts.

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Taking a look.

**Comment by kevhlee** [comment]
See <https://github.com/michaelmdelcavalcanti/liferay-portal/pull/8>.

**Pull request closed without merging**
