### PR TITLE
master qa 71948

### PR DESCRIPTION
**Pull request by kyle-miho**
[LRQA-71948](https://issues.liferay.com/browse/LRQA-71948)

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:Test:sf

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
Taking a look now.

**Comment by kevhlee** [comment]
See <https://github.com/kyle-miho/liferay-portal/pull/475>.

**Pull request closed without merging**
