### PR TITLE
LPS-185318 Create a check for the ServiceTrackerList wrong number of type arguments

### PR DESCRIPTION
**Pull request by kevhlee**
From @michaelmdelcavalcanti:

>Ticket: [LPS-185318](https://issues.liferay.com/browse/LPS-185318)
Hi Kevin!
Now me and @nicolas-sss are working together in UpgradeChecks.
This is a check for impls the class ServiceTrackerList. This pattern is about the quantity of arguments inside <> of ServiceTrackerList. The quantity of arguments was replaced from two to one. Please look at the UpgradeJavaServiceTrackerListCheck.testjava files if you have doubts.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
cc: @nicolas-sss, @natocesarrego

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
ci:forward

**Comment by nicolas-sss** [comment]
ci:forward

**Pull request closed without merging**
