### PR TITLE
LPS-154671 Allow filtered `SELECT` queries on Company table

### PR DESCRIPTION
**Pull request by kevhlee**
This is an update for [LPS-154671](https://issues.liferay.com/browse/LPS-154671). This pull request allows `SELECT` queries on the `Company` that use the `WHERE` clause. This is to allow cases like this: [WebIdToCompanyConfigurationPluginImpl.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/static/portal-configuration/portal-configuration-plugin-impl/src/main/java/com/liferay/portal/configuration/plugin/internal/WebIdToCompanyConfigurationPluginImpl.java#L83).

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
cc: @ling-alan-huang

**Comment by kevhlee** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@mbowerman Kevin made a fix here.
I am closing your [PR](https://github.com/ling-alan-huang/liferay-portal/pull/1807).

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
@ling-alan-huang, okay.

**Comment by kevhlee** [comment]
@ling-alan-huang,

Oh, nevermind. I misread your comment 😅. Disregard my previous comment.

**Comment by kevhlee** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
haha, my bad English, I should add a COMMA in the sentence.

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
Forwarded here: <https://github.com/brianchandotcom/liferay-portal/pull/133789>

**Pull request closed without merging**
