### PR TITLE
LPS-186054 Create a SF rule to Use ModelPermissions instead of serviceContext.setGuestPermissions() and serviceContext.setGroupPermissions()

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
Hi, Kevin.
If I understand Brian's questions correctly, I changed the test files by adding the groupPermissions and guestPermissions variables in each method that was using them, I also changed the name of the variable from sc to serviceContext2, I think it is necessary to explain that the variable has a different name because we want to test if the automation is correctly identifying with which variable it is manipulating.

Ticket: [LPS-186054](https://liferay.atlassian.net/browse/LPS-186054).

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
Hi @michaelmdelcavalcanti,

>I changed the test files by adding the groupPermissions and guestPermissions variables in each method that was using them...

I do not believe that was what Brian Chan was referring to. But we could keep the permission variables in there for now.

Also, while you corrected the variable naming., you did not correct the `if-else` branches. We cannot have the `else` branch in the same line of the closing brace of the `if`. So rather than this:

```java
if (condition) {
    ...
} else {
    ...
}
```

We have to have this:

```java
if (condition) {
    ...
}
else {
    ....
}
```

Please ___run SF___ on the test files. @nicolas-sss, can you help @michaelmdelcavalcanti with formatting the test files?

cc: @natocesarrego

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
Hi @kevhlee.
I have made the changes as requested. Later I ran SF on the expected file and checked the formatting applicable to that file, I found 2 SF changes, the first regarding the order of the imports that is not possible to insert organized, and the second regarding the new inserted lines being too long (80), these SF problems were already agreed with Brian that it is not possible to insert already formatted. I believe that now the test files are ok.
I look forward to your review.

**Comment by kevhlee** [comment]
ci:forward

**Pull request closed without merging**
