### PR TITLE
LPS-153072 Improve GradleBuildFileVisitor

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Kevin, please see https://liferay.slack.com/archives/D02V98D7KDK/p1661281069434289

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@kevhlee I am closing this one, becasue @Seiphon will work on this issue back again and he has a better approache for it.

**Comment by kevhlee** [comment]
Sounds good, @ling-alan-huang.

**Pull request closed without merging**
