### PR TITLE
LPS-185740 Update UpgradeJavaCheck

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
Hi, Kevin.
This is a check that returned oftentimes.

First return: Sort imports;
Second return: Change ArrayList to List;
Third return: Format content of the testcase following the SF guidelines.

Could you to check my PR?

thx

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
ci:teste:relevant

**Comment by michaelmdelcavalcanti** [comment]
Ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
ci:stop

**Comment by michaelmdelcavalcanti** [comment]
ci:test:stop

**Comment by michaelmdelcavalcanti** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:forward

**Comment by michaelmdelcavalcanti** [comment]
ci:forward

**Pull request closed without merging**
