### PR TITLE
LPS-188646 Rearrange method parameters for `FDSActionProvider.getDropdownItems()`

### PR DESCRIPTION
**Pull request by kevhlee**
From @michaelmdelcavalcanti:

>Hi, Kevin.
This check is identical to [LPS-186817](https://github.com/kevhlee/liferay-portal/pull/97) then I tried to make this check the same.
>
>Ticket: [LPS-188646](https://liferay.atlassian.net/browse/LPS-188646)

### CODE REVIEW

**Comment by kevhlee** [comment]
Hi @@michaelmdelcavalcanti,

Generally looks good, just made some minor changes and had to regenerate the docs to resolve merge conflicts.

One thing though is that this check basically does the same thing [LPS-186817](https://github.com/kevhlee/liferay-portal/pull/97) does. Because of this, I believe that these checks can be merged into one. You do not have to do this right now. But in the future, this might be a good idea because we are technically seeing duplication here.

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
Hi @@michaelmdelcavalcanti,

Generally looks good, just made some minor changes and had to regenerate the docs to resolve merge conflicts.

One thing though is that this check basically does the same thing [LPS-186817](https://github.com/kevhlee/liferay-portal/pull/97) does. Because of this, I believe that these checks can be merged into one. You do not have to do this right now. But in the future, this might be a good idea because we are technically seeing duplication here.

cc: @natocesarrego

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:forward

**Comment by michaelmdelcavalcanti** [comment]
ci:forward

**Comment by kevhlee** [comment]
Manually forwarded here: <https://github.com/brianchandotcom/liferay-portal/pull/137225>

**Pull request closed without merging**
