### PR TITLE
LPS-146967 Collections are not created correctly for extranet site initializer

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://issues.liferay.com/browse/LPS-146967>

__Notes:__
Issue caused by e73a1d2c6f64057f3638bbf20ebd69e0d8860f41.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks for the help @kevhlee!

**Comment by kevhlee** [comment]
No worries, @jkappler. Sorry about the blocker :)

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:forward

**Pull request closed without merging**
