### PR TITLE
LPS-190521 Update usages of `CPDefinitionService.fetchCPDefinitionByCProductExternalReferenceCode()`

### PR DESCRIPTION
**Pull request by kevhlee**

### CODE REVIEW

**Comment by kevhlee** [comment]
Hi @michaelmdelcavalcanti, please take a look at my commits.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:forward

**Comment by michaelmdelcavalcanti** [comment]
ci:reevaluate:1377401_13499

**Comment by michaelmdelcavalcanti** [comment]
ci:forward

**Comment by kevhlee** [comment]
ci:forward:force

**Comment by michaelmdelcavalcanti** [comment]
ci:close

**Pull request closed without merging**
