### PR TITLE
LPS-154006 Fix empty lines between same method in *UpgradeProcess.java

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-154006

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Hey Kevin,
It relates UpgradeProcess, can you help review?

**Comment by ling-alan-huang** [comment]
@kevhlee

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hi @ling-alan-huang, taking a look now.

**Comment by kevhlee** [comment]
LGTM for the most part, @ling-alan-huang!

Though the name of the SF check is slightly confusing since the description of the check is `"Finds missing and unnecessary empty lines."` I think the previous name (`JavaUpgradeEmptyLinesCheck`) would be better because it better describes what the check does.

/cc: @qz1010

**Comment by kevhlee** [comment]
Also, @ling-alan-huang, I think the description should be `"Finds missing and unnecessary empty lines in Upgrade classes."`

Everything else looks good.

**Comment by ling-alan-huang** [comment]
Thanks Kevin, I resent here: https://github.com/ling-alan-huang/liferay-portal/pull/1067

**Pull request closed without merging**
