### PR TITLE
LPS-187960 Update usage of `ModelListener`

### PR DESCRIPTION
**Pull request by kevhlee**

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
Hi @TamyrisTorres, please take a look at my changes and carefully observe what I have done. Let me know if there is anything I missed.

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
ci:forward

**Comment by kevhlee** [comment]
Manually forwarded here: <https://github.com/brianchandotcom/liferay-portal/pull/137621>

**Comment by TamyrisTorres** [comment]
Resubmitted because there was an error in the rebase - https://github.com/brianchandotcom/liferay-portal/pull/137832

**Pull request closed without merging**
