### PR TITLE
LPS-122910

### PR DESCRIPTION
**Pull request by ChrisKian**
Hey @kevhlee,
Please take a look and test my changes, and let me know how it goes.

My thoughts were to have the getTitle methods be uniform across the board, since one called the other.  with your initial changes, we would have had 2-3 different outcomes anywhere the getTitle method was called (one for each method, and one more for the ViewConflictsDisplayContext class call, since it gives a different title for null title as well).  With my changes, I'm hoping everything is now uniform, as well as any future use of the get title method(s).

Also, I left the final commit as optional, as there may be some unique business logic there which requires a different title for null model.  This probably isn't the case, but if you can confirm I'd appreciate it.

Let me know what you think, thanks!

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
Hey @ChrisKian,

I think making the title generation uniform across the different display contexts in `change-tracking-web` is a good idea. I had some difficulties working on this ticket because title generation wasn't consistent. I'll take a further look and test your changes tomorrow.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
Hey @ChrisKian,

The changes look great, but I do have one concern. I tested your changes and the issue is not reproducible. I also double-checked to make sure the method you deprecated is not being used anywhere. However, I would omit the last commit (<https://github.com/kevhlee/liferay-portal/pull/7/commits/c7726b3aa3d40e6a30110f29fb774f2074a1d7e9>) to be safe. Before <https://github.com/kevhlee/liferay-portal/pull/7/commits/c7726b3aa3d40e6a30110f29fb774f2074a1d7e9>, `ViewConflictsDisplayContext.java` used `CTDisplayRendererRegistry.getTypeName()` to generate a title, which only outputs the model's class name, whereas `CTDisplayRendererRegistry.getTitle()` would return both the model's class name and the model's primary key. These two methods generate slightly different outputs.

Other than that, rest of the commits should be good. Feel free to push forward.

**Comment by ChrisKian** [comment]
Thanks for looking at that @Kevhlee.  I'm aware my changes may produce a different 'title' value if the model is null, so I left these changes in a final, droppable commit.

The title value is purely visual, so adding a bit more detail shouldn't hurt anything.  I figure if we want the className and classPK in some situations, it wouldn't hurt to include it for all.  If this isn't the case, the commit can be dropped by engineering upon further review.

**Comment by ChrisKian** [comment]
Sent here: https://github.com/Preston-Crary/liferay-portal/pull/1257

**Comment by kevhlee** [comment]
Hey @ChrisKian ,

I took one more look at the code and you are probably correct. I did notice that these lines of code:

<https://github.com/kevhlee/liferay-portal/blob/c7726b3aa3d40e6a30110f29fb774f2074a1d7e9/modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/display/context/ViewConflictsDisplayContext.java#L224-L233>.

I think your last commit should be good.

**Pull request closed without merging**
