### PR TITLE
LPS-188646 Parameter order of the method  getDropdownItems was changed

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
Hi, Kevin.
This check is identical to [LPS-186817](https://github.com/kevhlee/liferay-portal/pull/97) then I tried to make this check the same.

Ticket: [LPS-188646](https://liferay.atlassian.net/browse/LPS-188646)

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
Taking a look.

**Comment by kevhlee** [comment]
By the way, in the future, you don't need to create a separate commit like this: 020d58cccfd78e1e32a8fa321f9cd24b0cea0536. It is not really necessary. You can do it when you create the check.

**Comment by kevhlee** [comment]
@michaelmdelcavalcanti, by the way, in the future, you don't need to create a separate commit like this: 020d58cccfd78e1e32a8fa321f9cd24b0cea0536. It is not really necessary. You can do it when you create the check.

**Comment by kevhlee** [comment]
See here: <https://github.com/kevhlee/liferay-portal/pull/103>

**Pull request closed without merging**
