### PR TITLE
LPS-181208 Refactor unit tests in SF

### PR DESCRIPTION
**Pull request by ling-alan-huang**
@kevhlee my only changes is 593c726c6ebe723beef8e1c0fca23e92dc440bd3

Btw, I think `com.liferay.source.formatter.processor` is not the proper package for `SourceProcessorTestParameters`, because `SourceProcessorTestParameters` is not a `SourceProcessor`, but I really don't have more proper package for it.

So, you can forward this PR if you don't want to move it. Your changes are good to go.

> Ticket: https://issues.liferay.com/browse/LPS-181208
> 
> Hi @ling-alan-huang,
> 
> I created this pull request to refactor unit tests in SF. The method overrides were getting confusing and the number of method parameters was getting too high. I decided to encapsulate all the test parameters into a class. Now, you have to create a SourceFormatterTestInput object for complicated test inputs. This approach should be extensible when more testing parameters need to be added.
> 
> I preserved the following methods for simple testing cases:
> 
> test(String fileName)
> test(String fileName, String expectedMessage)
> test(String fileName, String expectedMessage, int lineNumber)
> Let me know your thoughts.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hey @ling-alan-huang,

I also thought about the location of `SourceProcessorTestParameters` and I was not sure if I was putting it in the right package. I decided to put it in `com.liferay.source.formatter.processor` for now because it is a class that is used by the processors in that package.

**Comment by kevhlee** [comment]
ci:forward

**Pull request closed without merging**
