### PR TITLE
LPS-185518 Create a SF check for replace with searchContainer.setResultsAndTotal

### PR DESCRIPTION
**Pull request by TamyrisTorres**
Ticket: https://issues.liferay.com/browse/LPS-185518

Hello Kevin.
This check asks to replace the 'setResults' method with 'setResultsAndTotal'. Also, remove the 'setTotal' method.

You already reviewed this code, and you asked me about 'hasClassOrVariableName("SearchContainer", ' if it was necessary to have the name of the class. So, it's necessary because there are other '.setResults' and 'setTotal' methods in other classes, that aren't SearchContainer. That's why, I put this validation.

Can you review this pull request, please?

### CODE REVIEW

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Taking a look.

**Comment by kevhlee** [comment]
Hi @TamyrisTorres, I am going to wait on this pull request since you introduce new methods to `BaseSourceCheck` that is used in the other PRs.

Also, could you investigate the CI SF test failures? One of the test failures seem relevant.

**Comment by TamyrisTorres** [comment]
ci:test:sf

**Comment by TamyrisTorres** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
See here: <https://github.com/kevhlee/liferay-portal/pull/101>

**Pull request closed without merging**
